title: My Real Estate Site
baseurl: ""
url: "https://ak-real-estate-zm.netlify.app/"  # <- replace with your actual site URL

markdown: kramdown
theme: minima

collections:
  properties:
    output: true
    permalink: /properties/:slug/

permalink: pretty
