backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "listings"
    label: "Property Listings"
    folder: "content/listings"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }

