backend:
  name: github
  repo: walusungu101/Ak-real-estate-zm   # ✅ Replace with your actual repo if different
  branch: main

site_url: https://ak-real-estate-zm.netlify.app   # ✅ Update this to your Netlify site URL
logo_url: /images/logo.png                         # Optional CMS login logo

media_folder: "images/uploads"       # Where uploaded images go in repo
public_folder: "/images/uploads"     # How images appear on the website
collections:
  - name: "properties"
    label: "Properties"
    label_singular: "Property"
    folder: "properties"
    create: true
    slug: "{{slug}}"
    preview_path: "properties/{{slug}}"
    format: "yaml-frontmatter"
    extension: "md"
    output: true          # <-- HERE, aligned with above keys
    permalink: /properties/:slug/
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Negotiable", name: "negotiable", widget: "boolean", default: true }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Status", name: "status", widget: "string" }
      - { label: "Badge", name: "badge", widget: "string", required: false }
      - { label: "Beds", name: "beds", widget: "number", required: false }
      - { label: "Baths", name: "baths", widget: "number", required: false }
      - { label: "Garage", name: "garage", widget: "number", required: false }
      - { label: "Size", name: "size", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "property" }
