backend:
  name: github
  repo: walusungu101/Ak-real-estate-zm   # ✅ Required!
  branch: main

media_folder: "images/uploads"       # images will go here
public_folder: "/images/uploads"

collections:
  - name: "properties"
    label: "Properties"
    folder: "properties"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Negotiable", name: "negotiable", widget: "boolean", default: true }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Status", name: "status", widget: "string" }
      - { label: "Badge", name: "badge", widget: "string", required: false }
      - { label: "Beds", name: "beds", widget: "number", required: false }
      - { label: "Baths", name: "baths", widget: "number", required: false }
      - { label: "Garage", name: "garage", widget: "number", required: false }
      - { label: "Size", name: "size", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

